### ISSUE TITLE
Beyond in-memory caching

### ISSUE THREAD

**Issue by jhamman** [dask/cachey#21]
I've just started to use cachey (its quite cool, so thanks for making it). I'm curious if it would be possible to extend cache beyond in-memory caching, perhaps using Zict or similar mutable mappings.

Currently `Cache.data` is just a vanilla `dict`: 

https://github.com/dask/cachey/blob/382e55ee335ece4ad1295f6350b058ea3bac27fb/cachey/cache.py#L71

and I'm wondering if it could be any dict-like thing. A little monkey-patch exploration makes this seem possible. Here I replace `Cache.data` with Zict's `LRU` mapping:

```python
In [1]: >>> from cachey import Cache
   ...:
   ...: >>> c = Cache(1e9, 1)  # 1 GB, cut off anything with cost 1 or less

In [2]: c.data
Out[2]: {}

In [3]: import pickle
   ...: import zlib
   ...:
   ...: from zict import File, Func, LRU
   ...:
   ...: a = File('myfile/', mode='a')
   ...: b = Func(zlib.compress, zlib.decompress, a)
   ...: c = Func(pickle.dumps, pickle.loads, b)
   ...: d = LRU(100, c)

In [4]: d
Out[4]: <LRU: 0/100 on <Func: dumps<->loads <Func: compress<->decompress <File: myfile/, mode="a", 0 elements>>>>

In [5]: c = Cache(1e9)

# monkey patch here!
In [6]: c.data = d

In [7]: c
Out[7]: <cachey.cache.Cache at 0x7fc7c05ed6d8>

In [8]: c.data
Out[8]: <LRU: 0/100 on <Func: dumps<->loads <Func: compress<->decompress <File: myfile/, mode="a", 0 elements>>>>

In [9]: c.put('x', 'some value', cost=3)

In [10]: c.get('x')
Out[10]: 'some value'
```

Thoughts on what I've done here? What I'm really going for is a `Zict.Buffer` with a fast dict and a slower datastore (database or object store).

**Comment by mrocklin** [comment]
In principle this seems like it should be fine

**Comment by jhamman** [comment]
Thanks @mrocklin - thoughts on how this would be exposed?

Option 0: monkey-patch
```Python
c = Cache(...)
c.data = LRU(...)
```

Option 1: via the Cache constructor
```Python
c = Cache(..., cache_data=LRU(...))
```
Option 2: via a method of some kind
```Python
c = Cache(...)
c.set_cache_data(LRU(...))
```

I prefer option 1.

**Comment by TomAugspurger** [comment]
I also like option 1.

**Comment by mrocklin** [comment]
Yes, option 1 seems sensible to me.  This is also how we handle it in
related projects like Zict or Dask.

**Comment by jhamman** [comment]
Thanks @mrocklin and @TomAugspurger  - I opened #22 to discuss further.
